version: '3.8'

services:
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn portfolio.wsgi -b 0.0.0.0:8900
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=3#6d40ff4*7$$5pm3*tj=^mz2$$=nh$$4vq)#yngqlpi)-hxub!8u
      - DEBUG=False
    volumes:
      - .:/code
    ports:
      - 8900:8000
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: